drop table #series;
create table #series (x int not null);
insert into #series values (1), (2), (3), (4), (5), (6), (7), (8), (9), (10);
select * from #series;

SELECT x,                  SUM(x) OVER () FROM #series;
SELECT x, COUNT(x) OVER(), SUM(x) OVER () FROM #series;
SELECT x, COUNT(x) OVER w, SUM(x) OVER w  FROM #series WINDOW w AS ();
SELECT x, COUNT(x) OVER w, SUM(x) OVER w  FROM #series WINDOW w AS (ORDER BY X RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW);
SELECT x, COUNT(x) OVER w, SUM(x) OVER w  FROM #series WINDOW w AS (ORDER BY X ROWS  BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW);
SELECT x, COUNT(x) OVER w, SUM(x) OVER w  FROM #series WINDOW w AS (ORDER BY X ROWS UNBOUNDED PRECEDING);
SELECT x, COUNT(x) OVER w, SUM(x) OVER w  FROM #series WINDOW w AS (ORDER BY X ROWS BETWEEN CURRENT ROW AND CURRENT ROW);
SELECT x, COUNT(x) OVER w, SUM(x) OVER w  FROM #series WINDOW w AS (ORDER BY X ROWS CURRENT ROW);

SELECT x, COUNT(x) OVER w, SUM(x) OVER w  FROM #series WINDOW w AS (ORDER BY X ROWS BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING);

ROWS BETWEEN 1 PRECEDING AND CURRENT ROW)
ROWS BETWEEN CURRENT ROW AND 1 FOLLOWING)
(ROWS BETWEEN 3 PRECEDING AND CURRENT ROW


SELECT x, COUNT(x) OVER w, SUM(x) OVER w  FROM #series WINDOW w AS (PARTITION by x);
SELECT x, COUNT(x) OVER w, SUM(x) OVER w  FROM #series WINDOW w AS (PARTITION by x >= 3);


